services:
  - type: web
    name: chukwuemeka-obasi-lendsqr-be-test
    env: node
    plan: free 
    region: oregon
    buildCommand: |
      npm install
      npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: ~20
      - key: NODE_ENV
        value: production

      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        sync: false

      - key: JWT_SECRET
        sync: false
      
      - key: KARMA_PUBLIC_KEY
        sync: false
      - key: KARMA_SECRET_KEY
        sync: false

    build:
      command: |
        npm run build
        npm run migrate:latest